var genVar1 = ["he", "she"];

var genVar5 = ["He", "She"];

var genVar2 = ["him", "her"];

var genVar3 = ["his", "hers"];

var genVar4 = ["himself", "herself"]

var nameBank1 = ["Alex", "Sam", "Jo", "Cameron", "Avery", "Sam", "Kai", "Cody", "Devin", "Dylan", "Cody", "Corey", "Kai", "Jae", "Sam", "Adrian", "Kellan", "Max", "Taylor", "Corey", "Jessie"];

var nameBank2 = ["Corey", "Kyle", "Ryan", "Taylor", "Jo", "Kam", "Cameron", "Jay", "Alex", "Jordan", "Kay", "Rudy", "Quinn", "Jaime"];
var nameBank3 = ["Blake", "Kyle", "Alex"];

var newVignOne = "One day " + nameBank1[0] + " was shopping at the local supermarket. <br> Behind " + nameBank1[0] + " was another customer that had been bothering" + genVar2 + " throughout the shopping trip by blocking aisles, leaving items on the wrong shelves, and so on. <br> Annoyed, " + genVar1[1] + " took as much time as " + genVar1[1] + " could to scan each item, even though " + nameBank1[0] + " would be late for an important doctor visit. " + "Was" + nameBank1[0] + " justified in taking longer to scan each item?"


var newVignTwo = nameBank1[1] + " and " + nameBank2[0] + " have been dating for nearly three years. <br> The relationship has had its ups and downs. <br> Soon they are going to purchase a flat in the countryside. Normally they would always use a condom, but last night " + nameBank1[1] + " couldn't find a condom and " + nameBank2[0] + " forgot to pick them up. <br> " + nameBank2[0] + " opened up the backpack and found three condoms that have been there for five years. <br> " + nameBank1[1] + ' said, "It is okay we should just use it anyway." ' + nameBank2[0] + ' disagreed and insisted on not using the condom saying, "It is old, it would be just as risky to not use it."' + nameBank1[1] + " was angry and pushed " + nameBank2[0] + " in an attempt to get out of the room." + 'How justified was' + nameBank1[1] + ' in walking out of the room?'

var newVignThree = "Outside of the local shopping center there is a large traffic jam. <br> Drivers weave in an out of the traffic in an effort to get the most coveted spot. <br> " + nameBank1[2] + "  was trying to get the next closest spot to the entrance when " + genVar1[1] + " saw that the neighbor that has annoyed " + genVar2 + " for quite some time, was also vying for the same spot. <br> " + nameBank1[2] + "  took a risk and sped in an attempt to overtake the spot. <br> " + nameBank1[2] + "  got the spot instead of " + nameBank2[1] + ", but in the process scratched the front of the car on the curb. " + 'How justified was ' + nameBank1[2] + ' in cutting off the neighbor ' + nameBank2[1] + ', and taking the spot?'

var newVignFour = "Exam grades are due in the coming weeks. " + nameBank1[3] + " is the new instructor for a class of 400 students. <br>" + genVar5[1] + " had come up with a way to grade the largest " + " number of exams in the shortest time possible. <br>" + " What would have taken weeks took days, however, this process increased chances of errors. <br> One week before grades were due, " + nameBank2[2] + " the senior teaching assistant noticed some grading errors in many of the exams. " + genVar5[1] + " thought " + nameBank1[3] + " was constantly rude and didn't even care about the job. <br> In an effort to grade as quickly as possible " + nameBank1[3] + "made errors in nearly all of the exams. " + nameBank2[2] + " didn't say anything and jeopardized the grades of all the students in hoping that " + nameBank1[3] + " would be fired. " + "How justified was " + nameBank2[2] + " in not speaking up about the incorrect grading and jeopardizing not just the students grades but " + nameBank1[3] + "'s teaching position?"

var newVignFive = nameBank1[4] + " had recently broken off a 3-year relationship with " + nameBank2[3] + ", a local politician. <br> In " + nameBank2[3] + "'s mind the relationship was strong, often sharing how they both were feeling on a day to day basis. <br> Two weeks later at the pub with a mutual friend " + nameBank2[3] + " saw " + nameBank1[4] + " on a date. <br> " + nameBank2[3] + " saw on the news that " + nameBank1[0] + " is engaged and had been dating the now fiancé for over a year. <br> " + nameBank2[3] + ", drunk and angry, flipped the table " + nameBank1[0] + " and the fiancé were at. " + nameBank2[3] + " then used his position as a local politician to kick " + nameBank1[0] + " out of the pub and blacklist" + genVar2 + "from all the pubs in town. " + 'How justified was ' + nameBank2[3] + ' in getting ' + nameBank1[4] + ' banned from every pub in town?'

var newVignSix = nameBank1[5] + " is top of the class and is the model student often scoring the highest on exams. " + "Now at a prestigious university, " + nameBank1[5] + " was no longer the top student. What would take hours to finish now take days or weeks to finish. " + nameBank2[2] + " and " + nameBank1[5] + " became fast friends, but soon " + nameBank1[5] + " became jealous of how quickly things came to " + nameBank2[2] + ". In school " + nameBank1[5] + " was like " + nameBank2[2] + ", but now completely envious of " + genVar1[1] + ". The next exam was in a month on a difficult chapter of the text. In a jealous fit, " + genVar1[1] + " convinced " + nameBank2[2] + " to come with " + genVar2 + " without saying why. " + nameBank1[5] + " broke into the instructor’s computer to change the exam grades. " + "Both students were caught and suspended pending an investigation. " + " How justified was " + nameBank1[5] + " in bringing " + nameBank2[2] + " to the instructors office?"

var newVignSeven = "In three days " + nameBank1[6] + " has an important national exam for which " + genVar1[1] + " has been preparing for  nearly two months. " + "Scoring high on the exam means that " + genVar1[1] + " could be accepted to the top universities in the world. <br> " + nameBank1[6] + " was studying for the exam non-stop often forgetting to eat or drink. <br> The next two days " + nameBank1[6] + " didn't sleep at all. <br> The day before the exam, " + genVar1[1] + " passed out on the couch almost missing the exam. " + "Frantically e-mailing the exam instructor, " + nameBank1[6] + " lied and said " + genVar1[1] + " were very ill and would need to reschedule the exam. " + " How justified was " + nameBank1[6] + " in lying to the exam instructor on being ill?"

var newVignEight = nameBank1[7] + " has a difficult decision to make as a junior physician. <br> While going for a run through local park " + genVar1[1] + " run by a parent yelling at another parkgoer for BBQing on the grass. <br> The BBQer had every right to be there. <br> Later " + nameBank2[4] + ", the yelling parent, was choking on some food. <br> " + nameBank2[4] + ", recalling what happened early struggled with what to do but" + "ultimately decided not to help risking the standing as a physician. " + 'Do you think ' + nameBank1[7] + ' was justified in choosing not to help the' + nameBank2[4] + ' who was choking on some food?'

var newVignNine = "A family was camping for the first time in three years. <br> The parents bought each of the children a " + " special wand to roast marshmallows over the campfire. <br> Everyone in the family loved marshmallows but little " + nameBank1[8] + " was afraid of the fire.  " + nameBank1[8] + "'s oldest sibling " + nameBank2[5] + ", angry about " + nameBank1[8] + " always causing trouble and blaming " + genVar1[1] + " gave " + nameBank1[8] + " a marshmallow knowing " + genVar1[1] + " is too young. <br> The marshmallow quickly caught fire. <br> Scared of the fire, " + nameBank1[8] + " flung the marshmallow which landed on the forehead causing a small burn. <br> " + nameBank1[8] + " is only 8 years-old. " + " Do you think it was justified for" + nameBank1[8] + " to give the sibling " + nameBank2[5] + " a marshmallow to roast knowing they will hurt " + genVar4[1] + "?"

var newVignTen = "Normally there are 10 people working in the finances department, however today it was only " + nameBank1[9] + " working.<br> Often one of the other employees makes" + "some tea on the stove for the other workers. <br> However, as " + nameBank1[9] + " was alone " + genVar1[1] + " had to make the tea for " + genVar4 + ". <br> Well into the steeping on the stove " + nameBank1[9] + " forgot all  about the tea and soon started a fire in the kitchen. Firefighters investigated and discovered a fault in the electrical system that could have triggered the fire. " + nameBank1[9] + " was blamed by the bosses for the fire and swiftly fired. " + "How justified were " + nameBank1[9] + "'s bosses in firing " + genVar2[1] + "?"

var newVignEleven = nameBank1[10] + " and " + nameBank2[6] + " have been dating and living together for the past six years. <br> Soon after agreeing the relationship had become stale, both agreed on introducing a third person into the mix. <br> They both agreed to choose the person that they both were comfortable with. After " + nameBank3[0] + " was added to the relationship, " + nameBank2[6] + " became jealous of how much " + nameBank1[10] + " and " + nameBank3[0] + " had in common and appeared to be excluded from the relationship more and more. In a fit of rage/jealousy, " + nameBank2[6] + " threw out all of the mutual belongings to punish " + nameBank1[10] + " and " + nameBank3[0] + ". " + "Do you believe that " + nameBank1[10] + " was justified in the behavior toward " + nameBank2[6] + " and " + nameBank3[0] + "?"

var newVignTwelve = "It was " + nameBank1[11] + "'s turn to do the laundry for the rest of the household. <br> All the clothes were put into a pile and" + "normally would then be separated into white or colored clothing. <br> " + nameBank1[11] + " didn't think about separating the clothes, forgetting what can happen. <br> An hour later, while putting the clothes up to hang and dry, " + genVar1[1] + " noticed that all the white shirts were now a bright orange. <br> Unbeknownst to " + nameBank1[11] + ", there were a number of orange socks mixed in. " + nameBank2[7] + ", one of the roommates started screaming at " + genVar2[1] + " for the mistake trying to punch " + nameBank1[11] + " who then punched back. " + " Do you think " + nameBank1[11] + "'s response was justified?"

var newVignThirteen = nameBank1[12] + " is often called the know-it-all in the history course. <br> Whenever the instructor asks a question, " + nameBank1[12] + " is always the first to raise their hand. <br> So far in three months " + nameBank1[12] + " hasn't been stumped once. <br> Dr. Connors was soon becoming frustrated that " + nameBank1[12] + " was somehow showing " + genVar1[1] + " up. <br> Soon, Dr.Connors would start searching for the most obscure history facts. <br>" + nameBank1[12] + " became upset after Dr. Connors appeared very happy to have stumped" + genVar1[1] + ". " + " Do you think that Dr. Connors's behavior towards " + nameBank1[12] + " was justified?"

var newVignFourteen = nameBank1[13] + " is going out on the town for the first time in a couple months. <br> Exam season is" + "now over and " + genVar1[1] + " will soon graduate from University. <br> " + nameBank1[13] + "'s friends are going out to a club to celebrate all finishing and successfully graduating with honors. <br> At the club " + nameBank2[8] + " catches " + genVar1[1] + " eye. <br> They start dancing together and later go home together. <br> " + nameBank1[13] + " is currently dating " + nameBank2[8] + " who is going to university across the country. <br> " + nameBank1[13] + " wanted an open relationship and only mentioned it in passing. " + "How justified was " + nameBank1[13] + " in sleeping with someone other than " + nameBank2[8] + ", given " + genVar1[1] + " expressed " + genVar1[1] + " wanted to be in an open relationship in passing?";

var newVignFifteen = nameBank1[14] + " is meeting with a representative from the health department on issues concerning a virus discovered at the grocery store. " + nameBank1[14] + " is not following government guidelines of requiring facemasks. After the meeting " + nameBank1[14] + " still refuses to require facemasks stating that it makes face to face communication and forces employees not to wear any. The local government then instructs " + nameBank1[14] + " to close or " + genVar1[1] + " will incur high fines. " + " How justified was " + nameBank1[14] + " in refusing to require employees from wearing facemasks, against the guidelines of the city? 	"

var vignOne = nameBank1[15] + " and " + nameBank2[9] + " have been dating for 1 year. Three weeks ago, they both signed a one-year lease on a flat in the center of town. " + nameBank1[15] + " had a one-night stand with an acquaintance, " + nameBank3[1] + ", and got Chlamydia. " + nameBank1[15] + " apologized a week later, and " + nameBank2[9] + " accepted the apology. However, " + nameBank2[9] + " was still hurt and broke the lease and received a penalty from the letting agency. This also left the entirety of the rent to " + nameBank1[15] + ". " + " How justified do you think " + nameBank1[15] + " was in breaking the lease early?"

var vignTwo = nameBank1[16] + " has two friends, " + nameBank2[10] + " and " + nameBank3[2] + ", both for 10+ years. Both needed money from " + nameBank1[16] + ", but " + nameBank2[10] + " had spread an embarrassing secret to everyone. Furious, " + genVar1[1] + " gave more than enough money to " + nameBank3[2] + " and gave no money to " + nameBank2[10] + " even though agreeing to give " + nameBank2[10] + " money too. " + " Do you believe that " + nameBank1[16] + " was justified in not giving money to " + nameBank1[16] + "?"

var vignThree = nameBank1[17] + " had been dating " + nameBank2[11] + " for 3 years. They had just rented a new house in the suburbs, adopted a new dog, and were thinking of marriage. " + nameBank2[11] + " found out that " + nameBank1[17] + " having an ongoing affair with a coworker. " + nameBank2[11] + " decided to punish both by sleeping with as many people as " + genVar1[1] + " could get putting " + genVar4 + " and others at risk of infection. " + " Do you believe that " + nameBank1[17] + " was justified in getting back at " + nameBank1[17] + " by sleeping with as many people as " + genVar1[1] + " could?"

var vignFour = nameBank1[18] + " and " + nameBank2[12] + " have been married for 12 years, and have a boy and a girl, both under 10 years old. " + nameBank1[18] + " had fallen out of love with " + nameBank2[12] + " and filed for divorce and seeking full custody of the children. Both kids love " + nameBank2[12] + ", but " + nameBank1[18] + " was out to make sure that " + nameBank2[12] + " was punished, even if the children resent " + nameBank1[18] + ". " + " Was " + nameBank1[17] + " justified in seeking for a divorce?";

var vignFive = nameBank1[19] + " and " + nameBank2[13] + ", both criminals, stole a large amount of money from the bank. A week after the heist, " + nameBank2[13] + " found out that " + nameBank1[19] + " had been hoarding a lot of the money. " + nameBank1[19] + ", said " + genVar1[1] + " felt like " + genVar1[1] + " did more of the heist. Angry, " + nameBank2[13] + " turned both into the police. In " + genVar2[1] + ' mind, "If we do not split it both ways equal, then no one does.' + " Do you think that " + nameBank1[19] + " was justified in hoarding more of the money?	"

var vignSix = nameBank1[20] + " just turned sixteen. " + nameBank1[20] + "'s parents always insisted that " + genVar1[1] + " wait till marriage to have sex and often telling stories of the danger of STDs. In " + genVar2[1] + " mind it is the body and " + genVar1[1] + " can do what " + genVar1[1] + " want. " + nameBank1[20] + "'s parents soon found out that " + genVar1[1] + " have already had sex and grounded " + nameBank1[20] + " for 3-months. " + nameBank1[20] + " retaliated by going out and having risky sex with several partners, many of whom were older. " + " Do you think " + nameBank1[20] + " was justified in responding the way they did towards the parents?"